---
- name: Usando el modulo copy
  hosts: all
  remote_user: root
  tasks:
    - name: copiar un archivo a los hosts administrador y configurar sus atributos
      copy:
        src: files/users.txt
        dest: /home/devops/users.txt
        owner: devops
        group: devops
        mode: u+rw,g-ww,o-rwx
        setype: samba_share_t
