---
- name: configure system
  hosts: all
  remote_user: devops
  become: true
  tasks:
    - name: configure a custom /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
    - name: check file exists
      stat:
        path: /etc/motd
      register: motd
    - name: display stat results
      debug:
        var: motd
    - name: copy custom /etc/issue file
      copy:
        src: files/issue
        dest: /etc/issue
        owner: root
        group: root
        mode: 0644
    - name: Ensure /etc/issue.net is a sysmlink to /etc/issue
      file:
        src: /etc/issue
        dest: /etc/issue.net
        state: link
        owner: root
        group: root
        force: yes
